repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.24.0
    hooks:
      - id: golangci-lint
        stages: [commit-msg]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint
        args: [--fix]
        stages: [commit-msg]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.1
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-mod-tidy
        stages: [commit-msg]
      - id: go-fmt
        args: [--all-files]
        stages: [commit-msg]
  # Need to set path
  # - repo: local
  #   hooks:
  #     - id: tfproviderlint
  #       name: Provider lint error
  #       language: system
  #       entry: make provider-lint
