repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.24.0
    hooks:
      - id: golangci-lint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.1
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9
    hooks:
      - id: terraform-fmt